# Dockerfile.ui
FROM devopseasylearning/tarzan-ui:v0.0.1

ENV AUTH_HOST=auth \
    AUTH_PORT=8080 \
    WEATHER_HOST=weather \
    WEATHER_PORT=5000 \
    REDIS_USER=redis \
    REDIS_PASSWORD=redis

EXPOSE 3000
